### ISSUE TITLE
%patchX statement in .spec file without PatchX: declaration

### ISSUE THREAD

**Issue by dmacvicar** [moio/tetra#5]
Results in:
```
[110s] error: No patch number 0
```

https://build.opensuse.org/package/show/home:dmacvicar:java:tetra/HikariCP-java6

There is an extra %patch:

```
%prep
%setup -q -n src
%patch0 -p2
cp -f %{SOURCE1} .
cp -Rf %{_datadir}/tetra ../kit
```

**Comment by moio** [comment]
Fixed with 9b6d065, please install version 0.51 and re-run `tetra generate-spec`.

Thanks for reporting
