### ISSUE TITLE
Support for decompressing jar files is missing

### ISSUE THREAD

**Issue by renner** [moio/tetra#9]
Trying to create a tetra project based on sources packaged as `*.jar` fails to decompress the jarfile:

    $> tetra.ruby2.1 init saltstack-netapi-client-java ../../saltstack-lib-release/target/saltstack-netapi-client-0.4.0-sources.jar
    Project inited in saltstack-netapi-client-java/.
    Decompressing sources...
    Failed to run `tar xvf /devel/git/saltstack-lib-release/target/saltstack-netapi-client-0.4.0-sources.jar --directory src` (exit status 2)

**Comment by moio** [comment]
That's a strange usage of `jar`.

Usually `jar`red source archives just contain the project sources for debugging purposes, and they don't contain build scripts and any other resource needed to produce a working artifact. In all cases I can remember, the source jar archive is not the same archive that you can use to actually build something working.

I think in your case you need to start from the Git project snapshot:

```bash
wget https://github.com/SUSE/saltstack-netapi-client-java/archive/v0.4.0.tar.gz
tetra init saltstack-netapi-client-java v0.4.0.tar.gz
```

**Comment by renner** [comment]
That's right, it won't work with the jarred sources. Sorry for the noise, closing the issue.
